/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
 
INSERT INTO `stretchy_report` (`id`,`report_name`, `report_type`, `report_subtype`, `report_sql`, `description`, `core_report`, `use_report`) VALUES (188,'Loan Approved - API', 'API', 'Triggered', 'SELECT loan.`id` as loanId,loan.`loan_officer_id` as officerId,loan.`principal_amount_proposed` as loanAmount,loan.`submittedon_date`,loan.`approvedon_date`, loan.`disbursedon_date`, c.display_name as clientDisplayName, c.firstname as clientFirstName, loan.annual_nominal_interest_rate as annualInterestRate, s.firstname as officerFirstname, s.display_name as officerDisplayName FROM `m_loan` loan join m_client c on c.id = loan.client_id left join m_staff s on s.id = loan.loan_officer_id where loan.id = ${loanId} or ${loanId} = -1', 'Loan and client data of approved loan', '0', '0');
INSERT INTO `stretchy_report` (`id`,`report_name`, `report_type`, `report_subtype`, `report_sql`, `description`, `core_report`, `use_report`) VALUES (189,'Loan Created - API', 'API', 'Triggered', 'SELECT loan.`id` as loanId,loan.`loan_officer_id` as officerId,loan.`principal_amount_proposed` as loanAmount,loan.`submittedon_date`,loan.`approvedon_date`, loan.`disbursedon_date`, c.display_name as clientDisplayName, c.firstname as clientFirstName, loan.annual_nominal_interest_rate as annualInterestRate, s.firstname as officerFirstname, s.display_name as officerDisplayName FROM `m_loan` loan join m_client c on c.id = loan.client_id left join m_staff s on s.id = loan.loan_officer_id where loan.id = ${loanId} or ${loanId} = -1', 'Loan and client data of created loan', '0', '0');
INSERT INTO `stretchy_report` (`id`,`report_name`, `report_type`, `report_subtype`, `report_sql`, `description`, `core_report`, `use_report`) VALUES (190,'Loan Disbursed - API', 'API', 'Triggered', 'SELECT loan.`id` as loanId,loan.`loan_officer_id` as officerId,loan.`principal_amount_proposed` as loanAmount,loan.`submittedon_date`,loan.`approvedon_date`, loan.`disbursedon_date`, c.display_name as clientDisplayName, c.firstname as clientFirstName, loan.annual_nominal_interest_rate as annualInterestRate, s.firstname as officerFirstname, s.display_name as officerDisplayName FROM `m_loan` loan join m_client c on c.id = loan.client_id left join m_staff s on s.id = loan.loan_officer_id where loan.id = ${loanId} or ${loanId} = -1', 'Loan and client data of disbursed loan', '0', '0');
INSERT INTO `stretchy_report` (`id`,`report_name`, `report_type`, `report_subtype`, `report_sql`, `description`, `core_report`, `use_report`) VALUES (191,'Savings Account Created - API', 'API', 'Triggered', 'SELECT account.`id` as accountId,account.`account_no` as accountNumber,account.`nuban_account_number` as nubanAccountNumber, account.`submittedon_date`, c.display_name as clientDisplayName, c.firstname as clientFirstName FROM `m_savings_account` account join m_client c on c.id = account.client_id where account.id = ${savingsId} or ${savingsId} = -1', 'Savings account and client data of created account', '0', '0');
INSERT INTO `stretchy_report` (`id`,`report_name`, `report_type`, `report_subtype`, `report_sql`, `description`, `core_report`, `use_report`) VALUES (192,'Savings Account Deposit - API', 'API', 'Triggered', 'SELECT transaction.`id` as transactionId,account.`account_no` as accountNumber,account.`nuban_account_number` as nubanAccountNumber, transaction.`amount` as depositAmount, transaction.`transaction_date` as transactionDate, transaction.`running_balance_derived` as accountBalance, c.display_name as clientDisplayName, c.firstname as clientFirstName FROM `m_savings_account` account join m_client c on c.id = account.client_id join m_savings_account_transaction `transaction` on account.id = transaction.savings_account_id where transaction.id = ${savingsTransactionId} or ${savingsTransactionId} = -1', 'Savings transaction and client data of savings account', '0', '0');
INSERT INTO `stretchy_report` (`id`,`report_name`, `report_type`, `report_subtype`, `report_sql`, `description`, `core_report`, `use_report`) VALUES (193,'Savings Account Withdrawal - API', 'API', 'Triggered', 'SELECT transaction.`id` as transactionId,account.`account_no` as accountNumber,account.`nuban_account_number` as nubanAccountNumber, transaction.`amount` as withdrawalAmount, transaction.`transaction_date` as transactionDate, transaction.`running_balance_derived` as accountBalance, c.display_name as clientDisplayName, c.firstname as clientFirstName FROM `m_savings_account` account join m_client c on c.id = account.client_id join m_savings_account_transaction `transaction` on account.id = transaction.savings_account_id where transaction.id = ${savingsTransactionId} or ${savingsTransactionId} = -1', 'Loan and client data of approved loan', '0', '0');
INSERT INTO `stretchy_report` (`id`,`report_name`, `report_type`, `report_subtype`, `report_sql`, `description`, `core_report`, `use_report`) VALUES (194,'Loan Repayment - API', 'API', 'Triggered', 'SELECT loan.`id` as loanId, transaction.`amount` as transactionAmount, transaction.`transaction_date` as transactionDate, transaction.`outstanding_loan_balance_derived` as outstandingBalance, c.display_name as clientDisplayName, c.firstname as clientFirstName FROM `m_loan` loan join m_client c on c.id = loan.client_id join m_loan_transaction transaction on loan.id = transaction.loan_id where transaction.id = ${transactionId} or ${transactionId} = -1', 'Loan transaction and client data of repaid loan', '0', '0');
INSERT INTO `stretchy_report` (`id`,`report_name`, `report_type`, `report_subtype`, `report_sql`, `description`, `core_report`, `use_report`) VALUES (195,'Birthday Event - API', 'API', 'Triggered', 'SELECT c.display_name as clientDisplayName, c.firstname as clientFirstName, c.date_of_birth as dateOfBirth FROM m_client c where c.id = ${clientId} or ${clientId} = -1', 'Client information for birthday event', '0', '0');
INSERT INTO `stretchy_report` (`id`,`report_name`, `report_type`, `report_subtype`, `report_sql`, `description`, `core_report`, `use_report`) VALUES (196,'Special Event - API', 'API', 'Triggered', 'SELECT c.display_name as clientDisplayName, c.firstname as clientFirstName, c.date_of_birth as dateOfBirth FROM m_client c where c.id = ${clientId} or ${clientId} = -1', 'Client information for special event', '0', '0');

INSERT INTO `stretchy_report_parameter` (`report_id`, `parameter_id`, `report_parameter_name`) VALUES ('188', '1017', 'loanId');
INSERT INTO `stretchy_report_parameter` (`report_id`, `parameter_id`, `report_parameter_name`) VALUES ('189', '1017', 'loanId');
INSERT INTO `stretchy_report_parameter` (`report_id`, `parameter_id`, `report_parameter_name`) VALUES ('190', '1017', 'loanId');
INSERT INTO `stretchy_report_parameter` (`report_id`, `parameter_id`, `report_parameter_name`) VALUES ('191', '1021', 'savingsId');
INSERT INTO `stretchy_report_parameter` (`report_id`, `parameter_id`, `report_parameter_name`) VALUES ('192', '1022', 'savingsTransactionId');
INSERT INTO `stretchy_report_parameter` (`report_id`, `parameter_id`, `report_parameter_name`) VALUES ('193', '1022', 'savingsTransactionId');
INSERT INTO `stretchy_report_parameter` (`report_id`, `parameter_id`, `report_parameter_name`) VALUES ('194', '1006', 'transactionId');
INSERT INTO `stretchy_report_parameter` (`report_id`, `parameter_id`, `report_parameter_name`) VALUES ('195', '1018', 'clientId');
INSERT INTO `stretchy_report_parameter` (`report_id`, `parameter_id`, `report_parameter_name`) VALUES ('196', '1018', 'clientId');
